In [ ]:
# Pandas is newer package built on top of Numpy,and provides an efficient implementstion of a Data
#Frame ie a multidimensional array with attached rows and column lables
#often with heterogeneous types or missing data
# Pandas has series and df object
# both series and df have explicit index
#index is immutable
# NUMPYARRAY,PANDASDF,SERIES ARE ALL MUTABLE

In [ ]:
import numpy as np
import pandas as pd
data = pd.Series([0.25,0.5,0.75,1.0])

In [4]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [5]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [6]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
#while nupy has implied index,series has explicit index so we have more control over it

In [9]:
data = pd.Series([0.25,0.5,0.75,1.0],index=['a','b','c','d'])

In [10]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [11]:
data['c'] = 0.76

In [12]:
# series as specalised dictionary
population_dict = {'California':233333,'Texas':2344222,'New Delhi':4543333}

In [13]:
ps =  pd.Series(population_dict)

In [14]:
ps

California     233333
New Delhi     4543333
Texas         2344222
dtype: int64

In [15]:
df = pd.DataFrame(ps,columns=['population'])

In [16]:
df

population
California      233333
New Delhi      4543333
Texas          2344222

In [17]:
pd.DataFrame?

In [18]:
data = [{'a':i,'b':2*i}  #[{do some job} for loop]
    for i in range(3)]

In [19]:
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [20]:
data

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

In [21]:
population_dict = {'California':[233333,322222],'Texas':[2344222,233333],'New Delhi':[4543333,333333]}

In [22]:
pd.DataFrame(population_dict)

California  New Delhi    Texas
0      233333    4543333  2344222
1      322222     333333   233333

In [23]:
#[{do some job} for loop]
[{i:i+10} for i in range(10)]

[{0: 10},
 {1: 11},
 {2: 12},
 {3: 13},
 {4: 14},
 {5: 15},
 {6: 16},
 {7: 17},
 {8: 18},
 {9: 19}]

In [24]:
dct = [{'age':i+10,'height':i+20} for i in range(10)]

In [25]:
pdf = pd.DataFrame(dct)

In [26]:
pdf

age  height
0   10      20
1   11      21
2   12      22
3   13      23
4   14      24
5   15      25
6   16      26
7   17      27
8   18      28
9   19      29

In [27]:
pd.DataFrame(np.random.rand(3,2),columns=['foo','bar'],index=['a','b','c'])

foo       bar
a  0.019133  0.778733
b  0.064446  0.711799
c  0.310611  0.410156

In [28]:
pdf = pd.DataFrame(np.random.rand(3,2),columns=['foo','bar'],index=['a','b','c'])
pdf['foo']['b']
# can

0.65766410034854628

In [29]:
pdf

foo       bar
a  0.822657  0.634479
b  0.657664  0.636438
c  0.715582  0.754539

In [30]:
pdf['foo']['b']=0.99

In [31]:
pdf

foo       bar
a  0.822657  0.634479
b  0.990000  0.636438
c  0.715582  0.754539

In [32]:
pdf.keys

<bound method NDFrame.keys of         foo       bar
a  0.822657  0.634479
b  0.990000  0.636438
c  0.715582  0.754539>

In [33]:
A=np.zeros(4,dtype=[('A','i8'),('B','f8')])

In [34]:
A

array([(0,  0.), (0,  0.), (0,  0.), (0,  0.)], 
      dtype=[('A', '<i8'), ('B', '<f8')])

In [35]:
A =pd.DataFrame(A)

In [36]:
A

A    B
0  0  0.0
1  0  0.0
2  0  0.0
3  0  0.0

In [37]:
# INDEX AS ORDERED SETTO FACILITATE JOIN,SET ARITHMETIC ETC
indA = pd.Index([1,3,5,7,9])
indB = pd.Index([2,3,5,7,11])

In [38]:
#intersection or inner join
indA & indB

Int64Index([3, 5, 7], dtype='int64')

In [39]:
#union
indA | indB

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [40]:
# symmetric differences ,only includes where pairs match
indA ^ indB

Int64Index([1, 2, 9, 11], dtype='int64')

In [41]:
# DATA INDEXING AND SELECTION
data =  pd.Series([0.25,0.5,0.75,1.0,1.22],index=['a','b','c','d','e'])
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.22
dtype: float64

In [42]:
pdf = pd.DataFrame(data,columns=['ratio'])

In [43]:
pdf

ratio
a   0.25
b   0.50
c   0.75
d   1.00
e   1.22

In [44]:
pdf.loc['c':'e'] # explicit index

ratio
c   0.75
d   1.00
e   1.22

In [45]:
pdf.iloc[2:5] # implicit index/numerical

ratio
c   0.75
d   1.00
e   1.22

In [49]:
area =  pd.Series({'California':423967,'Texas':695662,'New York':141297,'Florida':170312})
pop = pd.Series({'California':1234567,'Texas':1692222,'New York':1401000,'Florida':1392111})

In [50]:
data = pd.DataFrame({'area':area,'pop':pop})

In [51]:
data

area      pop
California  423967  1234567
Florida     170312  1392111
New York    141297  1401000
Texas       695662  1692222

In [52]:
data['density']=data['pop']/data['area']

In [53]:
data

area      pop   density
California  423967  1234567  2.911941
Florida     170312  1392111  8.173887
New York    141297  1401000  9.915285
Texas       695662  1692222  2.432535

In [54]:
data.iloc[1:3] #iloc integer lookup # includes only 1,2

area      pop   density
Florida   170312  1392111  8.173887
New York  141297  1401000  9.915285

In [55]:
data.loc['Florida':'Texas'] # includes both florida and texas

area      pop   density
Florida   170312  1392111  8.173887
New York  141297  1401000  9.915285
Texas     695662  1692222  2.432535

In [56]:
data.ix[:'New York',:1] #ix hybrid of those two

/home/vijay/anaconda2/envs/py35/lib/python3.5/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  """Entry point for launching an IPython kernel.


area
California  423967
Florida     170312
New York    141297

In [57]:
# any of these can be used to set or modify df

In [58]:
# OPERATING ON DATA IN PANDAS
rng = np.random.RandomState(42)
df = pd.DataFrame(rng.randint(0,10,(3,4)),columns=['A','B','C','D'])

In [59]:
df

A  B  C  D
0  6  3  7  4
1  6  9  2  6
2  7  4  3  7

In [60]:
df1 = df['B']*2

In [61]:
df1

0     6
1    18
2     8
Name: B, dtype: int64

In [62]:
#OPERATION BETWEEN 2 SERIES ,PANDAS ALIGNS INDICIS IN THE PROCESS OF PERFORMING OPERATION
# MISSING INDICIS ARE GIVEN NAN
A = pd.Series([2,4,6],index=[0,1,2])
B = pd.Series([1,3,5],index=[1,2,3])

In [63]:
A

0    2
1    4
2    6
dtype: int64

In [64]:
B

1    1
2    3
3    5
dtype: int64

In [65]:
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [66]:
# YOU can fill values to make it match
A.add(B,fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [67]:
# similar alignment happens in df
A = pd.DataFrame(rng.randint(0,10,(2,2)),columns=['A','B'])
B = pd.DataFrame(rng.randint(0,10,(3,3)),columns=['B','A','C'])

In [68]:
A

A  B
0  7  2
1  5  4

In [69]:
B

B  A  C
0  1  7  5
1  1  4  0
2  9  5  8

In [70]:
A

A  B
0  7  2
1  5  4

In [71]:
A+B

A    B   C
0  14.0  3.0 NaN
1   9.0  5.0 NaN
2   NaN  NaN NaN

In [72]:
fill = A.stack().mean()
A.add(B,fill_value=fill)

A     B     C
0  14.0   3.0   9.5
1   9.0   5.0   4.5
2   9.5  13.5  12.5

python|pandas
+     |add()
-     |sub(),subtract()
*     |mul(),multiply()
/     |truediv(),div(),divide()
//    |floordiv()
%     |mod()
**    |pow()

In [73]:
#Operations between DF & series
A = rng.randint(10,size=(3,4))

In [74]:
A

array([[0, 9, 2, 6],
       [3, 8, 2, 4],
       [2, 6, 4, 8]])

In [75]:
A[0]

array([0, 9, 2, 6])

In [76]:
A-A[0] # NUMPY BRODCASTING RULES APPLY, see below

array([[ 0,  0,  0,  0],
       [ 3, -1,  0, -2],
       [ 2, -3,  2,  2]])

In [77]:
df = pd.DataFrame(A,columns=list('QRST'))
df

Q  R  S  T
0  0  9  2  6
1  3  8  2  4
2  2  6  4  8

In [78]:
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1  3 -1  0 -2
2  2 -3  2  2

In [79]:
df.subtract(df['R'],axis=0)

Q  R  S  T
0 -9  0 -7 -3
1 -5  0 -6 -4
2 -4  0 -2  2

In [80]:
#indicis are also auto aligned

In [81]:
halfrow =  df.iloc[0,::2]

In [82]:
halfrow

Q    0
S    2
Name: 0, dtype: int64

In [83]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1  3.0 NaN  0.0 NaN
2  2.0 NaN  2.0 NaN

In [84]:
# NaN and None in pandas , pandas handels both NaN(not a number)
vals2 =  np.array([1,np.nan,3,4])

In [85]:
vals2

array([  1.,  nan,   3.,   4.])

In [86]:
1+np.nan

nan

In [87]:
vals2.sum(),vals2.max(),vals2.min()

(nan, nan, nan)

In [88]:
vals2 =  np.array([1,np.nan,3,4,None])

In [89]:
vals2

array([1, nan, 3, 4, None], dtype=object)

In [90]:
ps =pd.Series([1, np.nan, 3, 4, None]) # series converts None to NaN of type float

In [91]:
# operations on null
ps.isnull()

0    False
1     True
2    False
3    False
4     True
dtype: bool

In [92]:
ps.notnull()

0     True
1    False
2     True
3     True
4    False
dtype: bool

In [93]:
ps.fillna(0)

0    1.0
1    0.0
2    3.0
3    4.0
4    0.0
dtype: float64

In [94]:
ps.dropna()

0    1.0
2    3.0
3    4.0
dtype: float64

In [95]:
df

Q  R  S  T
0  0  9  2  6
1  3  8  2  4
2  2  6  4  8

In [96]:
dfc =A+B

ValueError: operands could not be broadcast together with shapes (3,4) (3,3) 

In [ ]:
dfc

In [ ]:
dfc.dropna() # we can only drop full rows

In [ ]:
dfc.dropna(axis='columns')

In [ ]:
dfc.fillna(0)

In [ ]:
dfc

In [ ]:
# fill forward,back fill
dfc.fillna(method='ffill')

In [ ]:
dfc.fillna(method='bfill')

In [ ]:
dfc.fillna(method='ffill',axis=1) # row

In [ ]:
# HIERARCHICAL INDEX
# beyond one and two dimensional data
# This data is indexed by more than one or two keys

In [97]:
# we can expore considerations around indexing,slicing and computing stastics

In [98]:
#THE BAD WAY
index = [('California',2000),('California',2010),('New York',2000),('New York',2010), \
('Toronto',2000),('Toronto',2010)]
population = [223345,223566,12334,12456,22345,22456]

In [99]:
pop =  pd.Series(population,index=index)

In [100]:
pop

(California, 2000)    223345
(California, 2010)    223566
(New York, 2000)       12334
(New York, 2010)       12456
(Toronto, 2000)        22345
(Toronto, 2010)        22456
dtype: int64

In [101]:
pop[('New York', 2000):('Toronto', 2010)]

(New York, 2000)    12334
(New York, 2010)    12456
(Toronto, 2000)     22345
(Toronto, 2010)     22456
dtype: int64

In [102]:
# only good if you filter by both fields
#HOW DO YOU SELECT 2010 only?
pop[[i for i in pop.index if i[1]==2010]]

(California, 2010)    223566
(New York, 2010)       12456
(Toronto, 2010)        22456
dtype: int64

In [135]:
# THE RIGHT WAY #PANDAS MULTI INDEX

In [104]:
index =  pd.MultiIndex.from_tuples(index)

In [105]:
index

MultiIndex(levels=[['California', 'New York', 'Toronto'], [2000, 2010]],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [106]:
pop = pop.reindex(index)

In [107]:
pop

California  2000    223345
            2010    223566
New York    2000     12334
            2010     12456
Toronto     2000     22345
            2010     22456
dtype: int64

In [108]:
pop[:,2010]

California    223566
New York       12456
Toronto        22456
dtype: int64

In [121]:
pop['Toronto']

2000    22345
2010    22456
dtype: int64

In [109]:
#unstack converts a multiple indexed series into conventioanlly indexed df

In [110]:
pop_df = pop.unstack()

In [111]:
pop_df

2000    2010
California  223345  223566
New York     12334   12456
Toronto      22345   22456

In [112]:
pop_df = pop_df.stack()
pop_df

California  2000    223345
            2010    223566
New York    2000     12334
            2010     12456
Toronto     2000     22345
            2010     22456
dtype: int64

In [113]:
pop

California  2000    223345
            2010    223566
New York    2000     12334
            2010     12456
Toronto     2000     22345
            2010     22456
dtype: int64

In [114]:
# adding a new field
pop_df = pd.DataFrame({'total':pop,'under18':[9267089,9284094,4687374,432222,567777,677441]})

In [115]:
pop_df

total  under18
California 2000  223345  9267089
           2010  223566  9284094
New York   2000   12334  4687374
           2010   12456   432222
Toronto    2000   22345   567777
           2010   22456   677441

In [116]:
f_u18 = pop_df['under18']/pop_df['total']

In [117]:
f_u18

California  2000     41.492261
            2010     41.527307
New York    2000    380.036809
            2010     34.699904
Toronto     2000     25.409577
            2010     30.167483
dtype: float64

In [118]:
f_u18.unstack()

2000       2010
California   41.492261  41.527307
New York    380.036809  34.699904
Toronto      25.409577  30.167483

In [122]:
# METHODS OF MULTI INDEX CREATION

In [123]:
df = pd.DataFrame(np.random.rand(4,2),index=[['a','a','b','b'],[1,2,1,2]],columns=['data1','data2'])

In [124]:
df

data1     data2
a 1  0.513210  0.283546
  2  0.541145  0.186881
b 1  0.035669  0.887745
  2  0.486486  0.061862

In [125]:
# if you pass a dictionary with tuples as key, pandas will automatically recognise this
# as multiindex by default
dct = {('california',2000):234555,('Texas',2000):333332,('california',2010):443222,('Texas',2010):322322}

In [126]:
dct

{('Texas', 2000): 333332,
 ('Texas', 2010): 322322,
 ('california', 2000): 234555,
 ('california', 2010): 443222}

In [129]:
psrs=pd.Series(dct)

In [141]:
psrs.index.names=['place','year']

In [142]:
pd.DataFrame(psrs,columns=['population'])

population
place      year            
Texas      2000      333332
           2010      322322
california 2000      234555
           2010      443222

In [165]:
# 3 WAYS OF CREATIG MULTIINDEX
# ARRAYS,TUPLES AND PRODUCT
ind =pd.MultiIndex.from_arrays([['a','a','b','b'],[1,2,1,2]])
pd.MultiIndex.from_arrays([['a','a','b','b'],[1,2,1,2]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [161]:
sr =pd.Series([22,23,22,44],index=ind)

In [162]:
sr

a  1    22
   2    23
b  1    22
   2    44
dtype: int64

In [163]:
ind = pd.MultiIndex.from_tuples([('a',1),('a',2),('b',1),('b',2)])

In [164]:
ind

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [166]:
pd.MultiIndex.from_product([['a','b'],[1,2]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [168]:
# MULTIINDEXING COLUMNS
index = pd.MultiIndex.from_product([[2013,2014],[1,2]],names=['year','visit'])
index

MultiIndex(levels=[[2013, 2014], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]],
           names=['year', 'visit'])

In [169]:
columns = pd.MultiIndex.from_product([['Bob','Guido','Sakmos'],['HR','Temp']],names=['subject','type'])

In [170]:
columns

MultiIndex(levels=[['Bob', 'Guido', 'Sakmos'], ['HR', 'Temp']],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]],
           names=['subject', 'type'])

In [180]:
data = np.round(np.random.randn(4,6),1)
data[:,::2]*10
data +=37
data

array([[ 37.9,  35.3,  38.2,  33.8,  38.5,  38.9],
       [ 38. ,  36.1,  38.7,  37.5,  36.4,  37.8],
       [ 39.5,  38.1,  36.6,  38.1,  37.2,  37.4],
       [ 36.9,  38.7,  36. ,  38.7,  37.4,  37.1]])

In [181]:
health_data =  pd.DataFrame(data,index=index,columns=columns)

In [182]:
health_data

subject      Bob       Guido       Sakmos      
type          HR  Temp    HR  Temp     HR  Temp
year visit                                     
2013 1      37.9  35.3  38.2  33.8   38.5  38.9
     2      38.0  36.1  38.7  37.5   36.4  37.8
2014 1      39.5  38.1  36.6  38.1   37.2  37.4
     2      36.9  38.7  36.0  38.7   37.4  37.1

In [183]:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      38.2  33.8
     2      38.7  37.5
2014 1      36.6  38.1
     2      36.0  38.7

In [24]:
ser1 = pd.Series([10,10,10],index=[1,2,3])
ser2 = pd.Series([5,5,5],index=[1,5,6])
pd.concat([ser1,ser2]) # UNION

1    10
2    10
3    10
1     5
5     5
6     5
dtype: int64

In [3]:
#COMBINING DATA SETS CONCAT AND APPEND
ser1 = pd.Series(['A','B','C'],index=[1,2,3])
ser2 = pd.Series(['D','E','F'],index=[4,5,6])

In [5]:
pd.concat([ser1,ser2]) # UNION

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [16]:
def make_df(cols,ind):
    data = {c:[str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data,ind)
make_df('ABC',range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [20]:
ser1 = pd.Series(['A','B','C'],index=[1,2,3])
ser2 = pd.Series(['A','C','F'],index=[1,2,6])
df1= make_df('AB',[1,2])
df2= make_df('AB',[3,4])

In [21]:
pd.concat([df1,df2])

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [22]:
df1= make_df('AB',[1,2])
df2= make_df('AB',[1,4])

In [23]:
pd.concat([df1,df2])

A   B
1  A1  B1
2  A2  B2
1  A1  B1
4  A4  B4

In [33]:
ser1 = pd.Series([10,10,10],index=[2,1,3]) # series autoloins index dusing sum
ser2 = pd.Series([5,5,5],index=[1,5,6])

In [34]:
ser1

2    10
1    10
3    10
dtype: int64

In [35]:
ser2

1    5
5    5
6    5
dtype: int64

In [36]:
ser1+ser2

1    15.0
2     NaN
3     NaN
5     NaN
6     NaN
dtype: float64

In [40]:
df3 = make_df('AB',[0,1])
df4 = make_df('CD',[0,1])
print(df3)
print(df4)

    A   B
0  A0  B0
1  A1  B1
    C   D
0  C0  D0
1  C1  D1


In [65]:
pd.concat([df3,df4],axis=1)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1

In [44]:
pd.concat([df3,df4])

A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
0  NaN  NaN   C0   D0
1  NaN  NaN   C1   D1

In [46]:
x =  make_df('AB',[0,1])
y =  make_df('AB',[2,3])

In [47]:
x

A   B
0  A0  B0
1  A1  B1

In [48]:
y

A   B
2  A2  B2
3  A3  B3

In [50]:
pd.concat([x,y])

A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [51]:
x =  make_df('AB',[0,1])
y =  make_df('AB',[1,2])
pd.concat([x,y])

A   B
0  A0  B0
1  A1  B1
1  A1  B1
2  A2  B2

In [52]:
pd.concat([x,y],ignore_index=True) #ignores duplicate index

A   B
0  A0  B0
1  A1  B1
2  A1  B1
3  A2  B2

In [53]:
# adding multi index
pd.concat([x,y],keys=['x','y'])

A   B
x 0  A0  B0
  1  A1  B1
y 1  A1  B1
  2  A2  B2

In [55]:
# pd concat works with same column name but can be altered for different names 

In [62]:
#CONCATATION WITH JOINS,concat is like a join on column?
df5 = make_df('ABC',[1,2])
df6 = make_df('BCD',[3,4])

In [58]:
df5

A   B   C
1  A1  B1  C1
2  A2  B2  C2

In [59]:
df6

B   C   D
3  B3  C3  D3
4  B4  C4  D4

In [67]:
pd.concat([df5,df6]) # default is outer join of columns

A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

In [68]:
pd.concat([df5,df6],join='inner') # using inner join

B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

In [69]:
pd.concat([df5,df6],join_axes=[df5.columns]) # akin to left join

A   B   C
1   A1  B1  C1
2   A2  B2  C2
3  NaN  B3  C3
4  NaN  B4  C4

In [70]:
#there is an append keyword whih achives the same
df1

A   B
1  A1  B1
2  A2  B2

In [71]:
df2

A   B
1  A1  B1
4  A4  B4

In [73]:
df1.append(df2) # unlike in list the orignal df is not modilied

A   B
1  A1  B1
2  A2  B2
1  A1  B1
4  A4  B4

In [74]:
# MERGE AND JOIN
#pd.merge() function implements join
#one to one
#one to many
#many to many


In [11]:
df1 = pd.DataFrame({'employee':['Bob','Jake','Lisa','Sue','ZAP'],'group':['Accounting','Engineering',\
                                                                    'Engineering','HR','HR']})
df2 = pd.DataFrame({'employee':['Lisa','Bob','Jake','Sue','ZAP'],'hireDate':[2004,2008,\
                                                                    2012,2014,2004]})


In [12]:
df1

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
4      ZAP           HR

In [13]:
df2.sort_values('hireDate',ascending=False)

employee  hireDate
3      Sue      2014
2     Jake      2012
1      Bob      2008
0     Lisa      2004
4      ZAP      2004

In [19]:
df2.sort_values(['employee', 'hireDate'], ascending=[True, False])

employee  hireDate
1      Bob      2008
2     Jake      2012
0     Lisa      2004
3      Sue      2014
4      ZAP      2004

In [22]:
#one t0 one
df3 = pd.merge(df1,df2) # automatically recognises employee as join column (key)
df3 # the orignal index is disgarded, expect in left and right index join

employee        group  hireDate
0      Bob   Accounting      2008
1     Jake  Engineering      2012
2     Lisa  Engineering      2004
3      Sue           HR      2014

In [23]:
# many to one
df4 = pd.DataFrame({'group':['Accounting','Engineering','HR'],'supervisor':['Carly','Guido',\
                                                                    'Steve']})

In [24]:
df3

employee        group  hireDate
0      Bob   Accounting      2008
1     Jake  Engineering      2012
2     Lisa  Engineering      2004
3      Sue           HR      2014

In [25]:
df4

group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve

In [26]:
pd.merge(df3,df4)

employee        group  hireDate supervisor
0      Bob   Accounting      2008      Carly
1     Jake  Engineering      2012      Guido
2     Lisa  Engineering      2004      Guido
3      Sue           HR      2014      Steve

In [27]:
#many to many
df5 = pd.DataFrame({'group':['Accounting','Accounting','Engineering','Engineering',\
                            'HR','HR'],'skills':['math','spreadsheet','coding','linux',\
                                                                    'spreadsheet','org']})

In [28]:
df1

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [29]:
df5

group       skills
0   Accounting         math
1   Accounting  spreadsheet
2  Engineering       coding
3  Engineering        linux
4           HR  spreadsheet
5           HR          org

In [30]:
pd.merge(df1,df5) # like cross join? Yes

employee        group       skills
0      Bob   Accounting         math
1      Bob   Accounting  spreadsheet
2     Jake  Engineering       coding
3     Jake  Engineering        linux
4     Lisa  Engineering       coding
5     Lisa  Engineering        linux
6      Sue           HR  spreadsheet
7      Sue           HR          org

In [32]:
# SPECIFICATION OF MERGE KEY
# DEFAULT MERGE PICKS THE MATCHING COLUMN NAME
# IF COLUMN NAMES DO NOT MATCH USE ON KEY WORD
df1

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [33]:
df2

employee  hireDate
0     Lisa      2004
1      Bob      2008
2     Jake      2012
3      Sue      2014

In [34]:
pd.merge(df1,df2,on='employee')

employee        group  hireDate
0      Bob   Accounting      2008
1     Jake  Engineering      2012
2     Lisa  Engineering      2004
3      Sue           HR      2014

In [35]:
df3 = pd.DataFrame({'name':['Bob','Jake','Lisa','Sue'],'salary':[7000,8000,12000,9000]})

In [40]:
pd.merge(df1,df3,left_on='employee',right_on='name')

employee        group  name  salary
0      Bob   Accounting   Bob    7000
1     Jake  Engineering  Jake    8000
2     Lisa  Engineering  Lisa   12000
3      Sue           HR   Sue    9000

In [43]:
pd.merge(df1,df3,left_on='employee',right_on='name').drop('name',axis='columns') # or axis=1

employee        group  salary
0      Bob   Accounting    7000
1     Jake  Engineering    8000
2     Lisa  Engineering   12000
3      Sue           HR    9000

In [44]:
# similarly we can merge on index right_index and left_index

In [61]:
# df implements join() method, but df need to be indexed for it
df1a = df1.set_index('employee')
df2a =  df2.set_index('employee')

In [62]:
df2a

hireDate
employee          
Lisa          2004
Bob           2008
Jake          2012
Sue           2014

In [63]:
df1a
df1a.join(df2a)

group  hireDate
employee                       
Bob        Accounting      2008
Jake      Engineering      2012
Lisa      Engineering      2004
Sue                HR      2014

In [64]:
df1a

group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR

In [65]:
df3

name  salary
0   Bob    7000
1  Jake    8000
2  Lisa   12000
3   Sue    9000

In [66]:
pd.merge(df1a,df3,left_index=True,right_on='name') # combine index adn name

group  name  salary
0   Accounting   Bob    7000
1  Engineering  Jake    8000
2  Engineering  Lisa   12000
3           HR   Sue    9000

In [67]:
df6 =  pd.DataFrame({'name':['Peter','Paul','Mary'],'food':['fish','beans','bread']},\
                   columns=['name','food'])

In [69]:
df7 =  pd.DataFrame({'name':['Mary','Joseph'],'drink':['wine','beer']},\
                   columns=['name','drink'])

In [70]:
df6

name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

In [71]:
df7

name drink
0    Mary  wine
1  Joseph  beer

In [72]:
pd.merge(df6,df7) # default inner join

name   food drink
0  Mary  bread  wine

In [73]:
pd.merge(df6,df7,how='inner')

name   food drink
0  Mary  bread  wine

In [74]:
pd.merge(df6,df7,how='outer')

name   food drink
0   Peter   fish   NaN
1    Paul  beans   NaN
2    Mary  bread  wine
3  Joseph    NaN  beer

In [75]:
pd.merge(df6,df7,how='left')

name   food drink
0  Peter   fish   NaN
1   Paul  beans   NaN
2   Mary  bread  wine

In [78]:
# overlapping column names and suffixes keyword
df8 = pd.DataFrame({'name':['Bob','Jake','Lisa','Sui'],'rank':[1,2,3,4]})
df9 = pd.DataFrame({'name':['Bob','Sui','Lisa','Jake'],'rank':[1,2,3,4]})

In [79]:
df8

name  rank
0   Bob     1
1  Jake     2
2  Lisa     3
3   Sui     4

In [80]:
df9

name  rank
0   Bob     1
1   Sui     2
2  Lisa     3
3  Jake     4

In [82]:
pd.merge(df8,df9,on='name')

name  rank_x  rank_y
0   Bob       1       1
1  Jake       2       4
2  Lisa       3       3
3   Sui       4       2

In [84]:
pd.merge(df8,df9) # like inner join on all columns where name match

name  rank
0   Bob     1
1  Lisa     3

In [85]:
pd.merge(df8,df9,on='name',suffixes=["_L","_R"])

name  rank_L  rank_R
0   Bob       1       1
1  Jake       2       4
2  Lisa       3       3
3   Sui       4       2

## EXAMPLE US DATA SET

In [5]:
pop = pd.read_csv('data/state-population.csv')
areas = pd.read_csv('data/state-areas.csv')
abbrevs = pd.read_csv('data/state-abbrevs.csv')

In [16]:
pop.head(5)

state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

In [17]:
areas.head(5)

state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

In [18]:
abbrevs.head(5)

state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA

In [39]:
# RANK US STATES AND TERRITORIES BY THEIR 2010 POPULATION DENSITY

In [40]:
merged =  pd.merge(pop,abbrevs,how='outer',left_on='state/region',right_on='abbreviation')

In [41]:
merged.head()

state/region     ages  year  population    state abbreviation
0           AL  under18  2012   1117489.0  Alabama           AL
1           AL    total  2012   4817528.0  Alabama           AL
2           AL  under18  2010   1130966.0  Alabama           AL
3           AL    total  2010   4785570.0  Alabama           AL
4           AL  under18  2011   1125763.0  Alabama           AL

In [42]:
#merged = merged.drop('state/region',axis='columns')

In [43]:
#merged.head()

In [44]:
# check any mismatches in outer join
merged.isnull().any()

state/region    False
ages            False
year            False
population       True
state            True
abbreviation     True
dtype: bool

In [45]:
merged[merged['population'].isnull()].head()

state/region     ages  year  population state abbreviation
2448           PR  under18  1990         NaN   NaN          NaN
2449           PR    total  1990         NaN   NaN          NaN
2450           PR    total  1991         NaN   NaN          NaN
2451           PR  under18  1991         NaN   NaN          NaN
2452           PR    total  1993         NaN   NaN          NaN

In [48]:
merged[merged['population'].isnull()].tail()
# looks like all NaN values are from Puerto Rico and all before year 2000
# we alo see that some abbreviations are missing

state/region     ages  year  population state abbreviation
2463           PR    total  1998         NaN   NaN          NaN
2464           PR    total  1997         NaN   NaN          NaN
2465           PR  under18  1997         NaN   NaN          NaN
2466           PR    total  1999         NaN   NaN          NaN
2467           PR  under18  1999         NaN   NaN          NaN

In [49]:
merged.loc[merged['state'].isnull(),'state/region'].unique()

array(['PR', 'USA'], dtype=object)

In [56]:
# this can be fixed by filling appropriate entries
merged.loc[merged['state/region'] =='PR','state'] = 'Puerto Rico'
merged.loc[merged['state/region'] =='USA','state'] = 'United States'

In [57]:
merged.isnull().any()

state/region    False
ages            False
year            False
population       True
state           False
abbreviation     True
dtype: bool

In [ ]:
# no more nulls in state Yay