In [114]:
import pandas as pd                 # pandas is a dataframe library
import matplotlib.pyplot as plt     # matplotlib.pyplot plots data
import numpy as np                  # numpy provides N-dim object support

# do ploting inline instead of in a separate window
%matplotlib inline

In [4]:
#READ AND PARSE AIRLINE FILE
airline_tweets = pd.read_csv('airline_tweets.csv', usecols=['airline_sentiment','tweet_coord'],encoding='utf-8')
airline_tweets=airline_tweets.dropna()
airline_tweets=airline_tweets.loc[airline_tweets['tweet_coord'] != '[0.0, 0.0]']
sentiment_map = { 'negative' : 0,'neutral' :1,'positive' : 2}
airline_tweets['airline_sentiment'] = airline_tweets['airline_sentiment'].map(sentiment_map)
airline_tweets['tweet_coord'].replace(regex=True,inplace=True,to_replace=r'\[',value=r'')
airline_tweets['tweet_coord'].replace(regex=True,inplace=True,to_replace=r'\]',value=r'')
airline_tweets = airline_tweets.reset_index(drop=True)

split_c = airline_tweets['tweet_coord'].apply(lambda x: x.split(','))
airline_tweets['latitude'] = split_c.apply(lambda x: float(x[0]))
airline_tweets['longitude'] = split_c.apply(lambda x: float(x[1]))
airline_tweets.drop(['tweet_coord'],axis=1)

#READ AND PARSE CITIES
cities = pd.read_csv( "cities.csv", delimiter="," ,header='infer',usecols=['name','latitude','longitude'],encoding='utf-8')
cities=cities.dropna()
cities['city_coord']= cities[['latitude','longitude']].values.tolist()

In [5]:
airline_tweets[0:5]

airline_sentiment                 tweet_coord   latitude   longitude
0                  2   40.74804263, -73.99295302  40.748043  -73.992953
1                  0     42.361016, -71.02000488  42.361016  -71.020005
2                  1   33.94540417, -118.4062472  33.945404 -118.406247
3                  0  33.94209449, -118.40410103  33.942094 -118.404101
4                  2     33.2145038, -96.9321504  33.214504  -96.932150

In [6]:
cities[0:5]

name  latitude  longitude                      city_coord
0      les Escaldes  42.50729    1.53414   [42.507290000000005, 1.53414]
1  Andorra la Vella  42.50779    1.52109             [42.50779, 1.52109]
2    Umm al Qaywayn  25.56473   55.55517  [25.564729999999997, 55.55517]
3    Ras al-Khaimah  25.78953   55.94320             [25.78953, 55.9432]
4      Khawr Fakkān  25.33132   56.34199            [25.33132, 56.34199]

In [52]:
# find the nearest city to the tweet coorinates usin ckdtree(nearest neighbour) and query(Euclidean)
from scipy.spatial import cKDTree

def closest_pts(setA_lat, setA_lng, setB_lat, setB_lng):
    a_x = setA_lat.values
    a_y = setA_lng.values
    b_x = setB_lat.values
    b_y = setB_lng.values
    #print(a_x[0:5])
    a = np.c_[a_x, a_y]
    #print(a)
    b = np.c_[b_x, b_y]
    indx = cKDTree(b).query(a,k=1,p=2)[1]
    #print(indx)
    return pd.Series(b_x[indx]), pd.Series(b_y[indx]),pd.Series(cities['name'][indx])

In [53]:
setA_lat = airline_tweets['latitude']
setA_lng =  airline_tweets['longitude']

setB_lat = cities['latitude']
setB_lng =  cities['longitude']

In [54]:
c_x,c_y,c_n = closest_pts(setA_lat, setA_lng, setB_lat, setB_lng)

In [55]:
c_n[0:5]

21569    New York City
21062          Chelsea
22020       El Segundo
22020       El Segundo
20796           Frisco
Name: name, dtype: object

In [56]:
c_n = c_n.reset_index(drop=True)
c_n[0:5]

0    New York City
1          Chelsea
2       El Segundo
3       El Segundo
4           Frisco
Name: name, dtype: object

In [57]:
airline_tweets['nearest_latitude'] = c_x
airline_tweets['nearest_longitude'] = c_y
airline_tweets['nearest_city'] =c_n

In [59]:
airline_tweets[0:100]

airline_sentiment                 tweet_coord   latitude   longitude  \
0                   2   40.74804263, -73.99295302  40.748043  -73.992953   
1                   0     42.361016, -71.02000488  42.361016  -71.020005   
2                   1   33.94540417, -118.4062472  33.945404 -118.406247   
3                   0  33.94209449, -118.40410103  33.942094 -118.404101   
4                   2     33.2145038, -96.9321504  33.214504  -96.932150   
5                   1   34.0219817, -118.38591198  34.021982 -118.385912   
6                   1  33.57963333, -117.73024772  33.579633 -117.730248   
7                   0    40.6413712, -73.78311558  40.641371  -73.783116   
8                   2  36.08457854, -115.13780136  36.084579 -115.137801   
9                   1  37.79374402, -122.39327564  37.793744 -122.393276   
10                  0      26.074379, -80.1416831  26.074379  -80.141683   
11                  2   33.9469039, -118.40716847  33.946904 -118.407168   
12                  0  51.04345575, -114.06071363  51.043456 -114.060714   
13                  1   40.64662464, -73.77090177  40.646625  -73.770902   
14                  2  33.94652852, -118.40766257  33.946529 -118.407663   
15                  2    38.9128188, -77.00798226  38.912819  -77.007982   
16                  2   32.84359605, -96.84910929  32.843596  -96.849109   
17                  0    32.8437698, -96.84928399  32.843770  -96.849284   
18                  0   26.06726717, -80.14433663  26.067267  -80.144337   
19                  2     32.8454782, -96.8504585  32.845478  -96.850459   
20                  1   39.24087254, -94.63994975  39.240873  -94.639950   
21                  2  37.77465018, -122.44032176  37.774650 -122.440322   
22                  1  33.94696831, -118.40747994  33.946968 -118.407480   
23                  0   40.63767372, -74.11075451  40.637674  -74.110755   
24                  1   40.78986648, -73.10068286  40.789866  -73.100683   
25                  2    42.5696777, -71.42056878  42.569678  -71.420569   
26                  1  37.80065252, -122.43857414  37.800653 -122.438574   
27                  1  36.08546367, -115.31814055  36.085464 -115.318141   
28                  0   19.43706642, -99.07927123  19.437066  -99.079271   
29                  2    39.8621249, -104.6740909  39.862125 -104.674091   
..                ...                         ...        ...         ...   
70                  0   40.69814396, -74.17906717  40.698144  -74.179067   
71                  0  39.85790482, -104.67039013  39.857905 -104.670390   
72                  0  39.85799572, -104.67056217  39.857996 -104.670562   
73                  0     51.72050559, 8.72711201  51.720506    8.727112   
74                  0     29.7420124, -95.5606921  29.742012  -95.560692   
75                  0    40.6875448, -74.17714813  40.687545  -74.177148   
76                  0   19.43493094, -99.18877967  19.434931  -99.188780   
77                  0     29.7421541, -95.5600896  29.742154  -95.560090   
78                  0   41.97745295, -87.91025951  41.977453  -87.910260   
79                  0   41.97475934, -87.89040377  41.974759  -87.890404   
80                  2        51.322819, 5.3576218  51.322819    5.357622   
81                  0   41.97474769, -87.89039148  41.974748  -87.890391   
82                  0   41.97758466, -87.91065356  41.977585  -87.910654   
83                  0   29.98788997, -95.34470061  29.987890  -95.344701   
84                  0  45.52146907, -122.69810485  45.521469 -122.698105   
85                  0   41.97495038, -87.89005988  41.974950  -87.890060   
86                  0   29.98877308, -95.33846478  29.988773  -95.338465   
87                  0   41.97883697, -87.90639116  41.978837  -87.906391   
88                  1  45.67920767, -111.04847652  45.679208 -111.048477   
89                  0   41.97888728, -87.90617197  41.978887  -87.906172   
90                  0   33.64323551, -84.44248239  3

In [303]:
feature_df = airline_tweets[['nearest_city']]

In [304]:
label_df = airline_tweets['airline_sentiment']

In [305]:
type(feature_df)

pandas.core.frame.DataFrame

In [307]:
type(label_df)

pandas.core.series.Series

In [318]:
features = pd.get_dummies(feature_df, columns=["nearest_city"])
features[0:5]

nearest_city_Addison  nearest_city_Aldine  nearest_city_Aliso Viejo  \
0                     0                    0                         0   
1                     0                    0                         0   
2                     0                    0                         0   
3                     0                    0                         0   
4                     0                    0                         0   

   nearest_city_Allen  nearest_city_American Fork  nearest_city_Anaheim  \
0                   0                           0                     0   
1                   0                           0                     0   
2                   0                           0                     0   
3                   0                           0                     0   
4                   0                           0                     0   

   nearest_city_Angeles City  nearest_city_Annapolis  nearest_city_Arbutus  \
0                          0                       0                     0   
1                          0                       0                     0   
2                          0                       0                     0   
3                          0                       0                     0   
4                          0                       0                     0   

   nearest_city_Ashford           ...             nearest_city_Whitestone  \
0                     0           ...                                   0   
1                     0           ...                                   0   
2                     0           ...                                   0   
3                     0           ...                                   0   
4                     0           ...                                   0   

   nearest_city_Williamsport  nearest_city_Willow Grove  nearest_city_Windsor  \
0                          0                          0                     0   
1                          0                          0                     0   
2                          0                          0                     0   
3                          0                          0                     0   
4                          0                          0                     0   

   nearest_city_Winnipeg  nearest_city_Winter Park  \
0                      0                         0   
1                      0                         0   
2                      0                         0   
3                      0                         0   
4                      0                         0   

   nearest_city_Wolverhampton  nearest_city_Woodstock  nearest_city_Xiuying  \
0                           0                       0                     0   
1                           0                       0                     0   
2                           0                       0                     0   
3                           0                       0                     0   
4                           0                       0                     0   

   nearest_city_Zionsville  
0                        0  
1                        0  
2                        0  
3                        0  
4                        0  

[5 rows x 291 columns]

In [319]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(label_df.values)
print(list(le.classes_))
labels = le.transform(label_df)
labels[0:5]
#le.inverse_transform([0, 0, 1, 2])
#labels =  pd.get_dummies(label_df)
#labels[0:5]

[0, 1, 2]


array([2, 0, 1, 0, 2])

In [320]:
features.shape

(855, 291)

In [321]:
labels.shape

(855,)

In [322]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
lr_model =LogisticRegression(C=0.99, random_state=42)
train_features =  features
train_labels =  labels
lr_model.fit(train_features, train_labels)
lr_predict_class = lr_model.predict(train_features)

In [325]:
# training metrics
print("Accuracy: {0:.4f}".format(metrics.accuracy_score(train_labels, lr_predict_class)))
print(metrics.confusion_matrix(train_labels, lr_predict_class, labels=[0,1,2]) )
#print("")
print("Classification Report")
print(metrics.classification_report(train_labels, lr_predict_class, labels=[0,1,2]))

Accuracy: 0.6807
[[573   0   0]
 [129   3   0]
 [144   0   6]]
Classification Report
             precision    recall  f1-score   support

          0       0.68      1.00      0.81       573
          1       1.00      0.02      0.04       132
          2       1.00      0.04      0.08       150

avg / total       0.78      0.68      0.56       855

